# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/Ray/Vivado/CPU54/CPU54.runs/synth_1/.Xil/Vivado-10516-RayBeast/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a100tcsg324-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      D:/Ray/Vivado/CPU54/CPU54.runs/synth_1/.Xil/Vivado-10516-RayBeast/realtime/imem_stub.v
      D:/Ray/Vivado/CPU54/CPU54.srcs/sources_1/new/mult.v
      D:/Ray/Vivado/CPU54/CPU54.srcs/sources_1/new/regfile.v
      D:/Ray/Vivado/CPU54/CPU54.srcs/sources_1/new/pc.v
      D:/Ray/Vivado/CPU54/CPU54.srcs/sources_1/new/multu.v
      D:/Ray/Vivado/CPU54/CPU54.srcs/sources_1/new/hilo.v
      D:/Ray/Vivado/CPU54/CPU54.srcs/sources_1/new/ext.v
      D:/Ray/Vivado/CPU54/CPU54.srcs/sources_1/new/divu.v
      D:/Ray/Vivado/CPU54/CPU54.srcs/sources_1/new/div.v
      D:/Ray/Vivado/CPU54/CPU54.srcs/sources_1/new/cp0.v
      D:/Ray/Vivado/CPU54/CPU54.srcs/sources_1/new/control.v
      D:/Ray/Vivado/CPU54/CPU54.srcs/sources_1/new/cnw.v
      D:/Ray/Vivado/CPU54/CPU54.srcs/sources_1/new/clz.v
      D:/Ray/Vivado/CPU54/CPU54.srcs/sources_1/new/alu.v
      D:/Ray/Vivado/CPU54/CPU54.srcs/sources_1/new/add.v
      D:/Ray/Vivado/CPU54/CPU54.srcs/sources_1/new/cpu.v
      D:/Ray/Vivado/CPU54/CPU54.srcs/sources_1/new/dmem.v
      D:/Ray/Vivado/CPU54/CPU54.srcs/sources_1/new/sccomp_dataflow2.v
      D:/Ray/Vivado/CPU54/CPU54.srcs/sources_1/new/seg7x16.v
      D:/Ray/Vivado/CPU54/CPU54.srcs/sources_1/new/divider.v
      D:/Ray/Vivado/CPU54/CPU54.srcs/sources_1/new/cpu_onboard.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList D:/Ray/Vivado/CPU54/CPU54.runs/synth_1/.Xil/Vivado-10516-RayBeast/realtime/cpu_onboard_test_synth.xdc
    rt::sdcChecksum
    set rt::top cpu_onboard_test
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {D:/Ray/Vivado/CPU54/CPU54.cache/wt}
    rt::set_parameter enableSplitFlowPath "D:/Ray/Vivado/CPU54/CPU54.runs/synth_1/.Xil/Vivado-10516-RayBeast/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
      rt::run_synthesis -module $rt::top
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
